---
title: "hw1"
author:
    - YangTengchao
documentclass: ctexart
geometry: "left=2.5cm,right=2cm,top=3cm,bottom=2.5cm"
output:
  pdf_document: default
  html_notebook: default
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---
```{r step1}
# 引入数据
load("pirates.RData")
```
```{r step2}
# 问题调查
# Body piercing data
american.bp <- c(3, 5, 2, 1, 4, 4, 6, 3, 5, 4)
european.bp <- c(6, 5, 7, 7, 6, 3, 4, 6, 5, 4)
# Store data in a datafram
ebp.survey <- data.frame("bp" = c(american.bp, european.bp),
"group" = rep(c("American","European"), each = 10),stringsAsFactors = FALSE)
```
```{r step3,warning=FALSE}
# 箱线图判断
boxplot(bp ~ group, data = ebp.survey, 
        main = "海盗身体穿孔数目箱线图",
        xlab = "地区", ylab = "穿孔数目")
# 对于中位数，欧洲地区的穿孔数目比美国高；同时说明欧洲地区穿孔数目多的人较多
# 对于上下四分位数，可以看出欧洲地区穿孔数目主要集中在中间数目的水平；美国地区数目集中在中间偏大水平
# 但从箱的长度可以看出其离散程度相差不大
```
```{r step4}
# t.test判断美国和欧洲穿孔数目差异
p.test <- t.test(bp ~ group, data = ebp.survey)
p.test
# 可以看出欧洲和美国穿孔数目有差异
# 可以看出p值为0.0214 < 0.05，说明在置信度0.95的情况下
# 可以拒绝原假设，说明差异显著
```
```{r step5}
# t.test判断29、30岁纹身差异
t.test <- t.test(tattoos ~ age, data = pirates, subset = age %in% c(29, 30))
t.test
# 没有足够证据证明29、30纹身情况存在差异
# 可以看出p值0.7911 > 0.05，在置信度为0.95的情况下
# 没有足够证据拒绝原假设，因此不能说明由显著差异
```
```{r step6}
# 卡方检验大学和佩戴眼罩是否有关联
c.test <- chisq.test(table(pirates$eyepatch, pirates$college))
c.test
# 没有足够证据证明大学和眼罩有关联
# 可以看出p值1 > 0.05，在置信度为0.95的情况下
# 没有足够证据拒绝原假设，因此不能说明两者有关联
```



